export const allGoogleFonts = [
    "Roboto",
    "Open Sans",
    "Noto Sans JP",
    "Lato",
    "Montserrat",
    "Poppins",
    "Source Sans Pro",
    "Roboto Condensed",
    "Oswald",
    "Roboto Mono",
    "Raleway",
    "Noto Sans",
    "Ubuntu",
    "Inter",
    "Nunito",
    "Roboto Slab",
    "Merriweather",
    "PT Sans",
    "Playfair Display",
    "Mukta",
    "Noto Sans KR",
    "Rubik",
    "Nunito Sans",
    "Work Sans",
    "Noto Sans TC",
    "Lora",
    "Fira Sans",
    "Nanum Gothic",
    "Quicksand",
    "Titillium Web",
    "Barlow",
    "PT Serif",
    "Hind Siliguri",
    "Mulish",
    "Inconsolata",
    "Noto Serif",
    "Heebo",
    "Karla",
    "Libre Franklin",
    "Josefin Sans",
    "IBM Plex Sans",
    "Noto Sans SC",
    "Libre Baskerville",
    "Bebas Neue",
    "Oxygen",
    "Dosis",
    "Kanit",
    "Arimo",
    "PT Sans Narrow",
    "Source Code Pro",
    "DM Sans",
    "EB Garamond",
    "Anton",
    "Cabin",
    "Bitter",
    "Source Serif Pro",
    "Lobster",
    "Cairo",
    "Dancing Script",
    "Signika Negative",
    "Barlow Condensed",
    "Noto Sans HK",
    "Hind",
    "Prompt",
    "Yanone Kaffeesatz",
    "Abel",
    "M PLUS Rounded 1c",
    "Fjalla One",
    "Manrope",
    "Comfortaa",
    "Varela Round",
    "Pacifico",
    "Exo 2",
    "Merriweather Sans",
    "Maven Pro",
    "Arvo",
    "Overpass",
    "Noto Serif JP",
    "Asap",
    "Teko",
    "Hind Madurai",
    "Indie Flower",
    "Shadows Into Light",
    "Domine",
    "Abril Fatface",
    "Fira Sans Condensed",
    "Cormorant Garamond",
    "Patrick Hand",
    "Permanent Marker",
    "IBM Plex Serif",
    "Slabo 27px",
    "Assistant",
    "Secular One",
    "Questrial",
    "Rajdhani",
    "Padauk",
    "Catamaran",
    "Archivo",
    "Caveat",
    "Barlow Semi Condensed",
    "Alfa Slab One",
    "Zilla Slab",
    "Red Hat Display",
    "Jost",
    "Public Sans",
    "Tajawal",
    "Satisfy",
    "Archivo Narrow",
    "ABeeZee",
    "Space Grotesk",
    "Fredoka One",
    "Play",
    "Acme",
    "Signika",
    "Bree Serif",
    "Exo",
    "Nanum Myeongjo",
    "Noto Sans Display",
    "Space Mono",
    "Cookie",
    "IBM Plex Mono",
    "Amatic SC",
    "Vollkorn",
    "Saira Condensed",
    "M PLUS 1p",
    "Righteous",
    "Chakra Petch",
    "Martel",
    "Sarabun",
    "Alegreya Sans",
    "Cinzel",
    "Yantramanav",
    "Patua One",
    "Alegreya",
    "Courgette",
    "Didact Gothic",
    "Ubuntu Condensed",
    "Amiri",
    "Paytone One",
    "Crete Round",
    "Tinos",
    "Antic Slab",
    "Baloo 2",
    "Frank Ruhl Libre",
    "Cardo",
    "Russo One",
    "Archivo Black",
    "Kalam",
    "PT Sans Caption",
    "Great Vibes",
    "Staatliches",
    "DM Serif Display",
    "Changa",
    "Lobster Two",
    "Kaushan Script",
    "Prata",
    "Francois One",
    "Asap Condensed",
    "Montserrat Alternates",
    "Noticia Text",
    "Parisienne",
    "Almarai",
    "Orbitron",
    "Noto Serif TC",
    "Koulen",
    "Sacramento",
    "Gloria Hallelujah",
    "Lexend Deca",
    "Spectral",
    "Quattrocento Sans",
    "Pathway Gothic One",
    "Cormorant",
    "Old Standard TT",
    "Sawarabi Mincho",
    "Cuprum",
    "Quattrocento",
    "Noto Kufi Arabic",
    "Concert One",
    "Rokkitt",
    "Playfair Display SC",
    "Encode Sans",
    "Chivo",
    "Gelasio",
    "Alata",
    "Volkhov",
    "Press Start 2P",
    "Monda",
    "Titan One",
    "Eczar",
    "Luckiest Guy",
    "Josefin Slab",
    "El Messiri",
    "Cantarell",
    "Yellowtail",
    "Passion One",
    "Special Elite",
    "Antonio",
    "Unna",
    "Saira",
    "Advent Pro",
    "Gothic A1",
    "PT Mono",
    "News Cycle",
    "Lexend",
    "Outfit",
    "Boogaloo",
    "Faustina",
    "Ropa Sans",
    "Neuton",
    "Poiret One",
    "Fira Sans Extra Condensed",
    "Yeseva One",
    "Vidaloka",
    "Handlee",
    "Sora",
    "Architects Daughter",
    "Philosopher",
    "Bangers",
    "Ultra",
    "Khand",
    "Marcellus",
    "Mitr",
    "Carter One",
    "Noto Sans Arabic",
    "Creepster",
    "Lusitana",
    "Playball",
    "Sawarabi Gothic",
    "Noto Serif KR",
    "Alice",
    "Quantico",
    "Viga",
    "Tangerine",
    "Sanchez",
    "Noto Serif SC",
    "Ubuntu Mono",
    "Mali",
    "Pragati Narrow",
    "Macondo",
    "Saira Semi Condensed",
    "Fugaz One",
    "Hammersmith One",
    "Taviraj",
    "Homemade Apple",
    "Aleo",
    "Amaranth",
    "Pangolin",
    "Ruda",
    "Istok Web",
    "Karma",
    "Jura",
    "Allura",
    "Marck Script",
    "Neucha",
    "Reenie Beanie",
    "Palanquin",
    "DM Serif Text",
    "Gudea",
    "Hind Vadodara",
    "Nanum Gothic Coding",
    "Cabin Condensed",
    "Arima Madurai",
    "Merienda",
    "IBM Plex Sans Condensed",
    "Syncopate",
    "Alegreya Sans SC",
    "Rock Salt",
    "Khula",
    "Fira Code",
    "Bungee",
    "Armata",
    "Bai Jamjuree",
    "Actor",
    "Adamina",
    "Arsenal",
    "Monoton",
    "Rubik Mono One",
    "Commissioner",
    "Oleo Script",
    "Caveat Brush",
    "Encode Sans Condensed",
    "Mukta Malar",
    "Crimson Pro",
    "Ramabhadra",
    "Varela",
    "Covered By Your Grace",
    "BenchNine",
    "Gentium Basic",
    "Kosugi Maru",
    "Stint Ultra Condensed",
    "Alex Brush",
    "Mada",
    "Sen",
    "Sriracha",
    "Mr Dafoe",
    "Source Serif 4",
    "Bad Script",
    "Cousine",
    "Julius Sans One",
    "Nanum Pen Script",
    "Pontano Sans",
    "Unica One",
    "Alef",
    "Sigmar One",
    "Arapey",
    "Audiowide",
    "Electrolize",
    "Itim",
    "Martel Sans",
    "Abhaya Libre",
    "Damion",
    "Cantata One",
    "Red Hat Text",
    "Gochi Hand",
    "Noto Naskh Arabic",
    "Niramit",
    "Sintony",
    "Tenor Sans",
    "Gruppo",
    "Economica",
    "Gentium Book Basic",
    "Sarala",
    "Balsamiq Sans",
    "Black Han Sans",
    "Sorts Mill Goudy",
    "Bodoni Moda",
    "Rufina",
    "Lilita One",
    "Shrikhand",
    "Share Tech Mono",
    "Nothing You Could Do",
    "Basic",
    "Fira Mono",
    "Allerta Stencil",
    "Forum",
    "Black Ops One",
    "Literata",
    "Bubblegum Sans",
    "Castoro",
    "Lalezar",
    "IBM Plex Sans Arabic",
    "Baskervville",
    "Jaldi",
    "Aclonica",
    "Yrsa",
    "Blinker",
    "Six Caps",
    "Palanquin Dark",
    "Urbanist",
    "Coda",
    "Noto Serif Display",
    "Fredericka the Great",
    "Chewy",
    "Laila",
    "Italianno",
    "Glegoo",
    "Overlock",
    "Be Vietnam Pro",
    "Shadows Into Light Two",
    "Belgrano",
    "Antic",
    "Allerta",
    "Anonymous Pro",
    "Changa One",
    "Lemonada",
    "Sansita",
    "Courier Prime",
    "Pinyon Script",
    "Spinnaker",
    "Reem Kufi",
    "Berkshire Swash",
    "Rancho",
    "Niconne",
    "Enriqueta",
    "Kreon",
    "Voltaire",
    "Darker Grotesque",
    "Average Sans",
    "Hind Guntur",
    "Squada One",
    "Aldrich",
    "Krub",
    "Noto Sans Tamil",
    "Corben",
    "PT Serif Caption",
    "Pridi",
    "Kameron",
    "Cutive Mono",
    "Cabin Sketch",
    "Days One",
    "Holtwood One SC",
    "Noto Sans Thai",
    "Annie Use Your Telescope",
    "Londrina Solid",
    "Candal",
    "Markazi Text",
    "Libre Caslon Text",
    "Charm",
    "Alike Angular",
    "Michroma",
    "Coming Soon",
    "Norican",
    "IM Fell English SC",
    "Comic Neue",
    "Judson",
    "Mrs Saint Delafield",
    "Bevan",
    "Bowlby One SC",
    "Herr Von Muellerhoff",
    "VT323",
    "Just Another Hand",
    "Marcellus SC",
    "Saira Extra Condensed",
    "Nanum Brush Script",
    "Arizonia",
    "Short Stack",
    "Caudex",
    "Leckerli One",
    "Gilda Display",
    "Racing Sans One",
    "Rozha One",
    "Skranji",
    "Suez One",
    "Mukta Vaani",
    "Graduate",
    "Krona One",
    "Athiti",
    "STIX Two Text",
    "Rambla",
    "K2D",
    "Lateef",
    "Capriola",
    "Rye",
    "Rochester",
    "Alatsi",
    "Amita",
    "Do Hyeon",
    "Oranienbaum",
    "Cinzel Decorative",
    "Baloo Da 2",
    "Noto Sans Devanagari",
    "Delius",
    "Kumbh Sans",
    "Pompiere",
    "BioRhyme",
    "Scada",
    "Cormorant Infant",
    "Yesteryear",
    "Cambay",
    "Belleza",
    "Mate",
    "GFS Didot",
    "Telex",
    "Noto Sans Malayalam",
    "Mandali",
    "Jua",
    "Magra",
    "Henny Penny",
    "Trocchi",
    "Overpass Mono",
    "Syne",
    "Biryani",
    "Kristi",
    "Miriam Libre",
    "Arbutus Slab",
    "Carrois Gothic",
    "Epilogue",
    "Big Shoulders Display",
    "David Libre",
    "Readex Pro",
    "Rammetto One",
    "Bungee Inline",
    "Fauna One",
    "Trirong",
    "Pattaya",
    "Noto Serif Bengali",
    "Nobile",
    "Average",
    "Copse",
    "Cedarville Cursive",
    "Halant",
    "Nixie One",
    "Hi Melody",
    "JetBrains Mono",
    "NTR",
    "Alegreya SC",
    "Quintessential",
    "La Belle Aurore",
    "Amethysta",
    "Contrail One",
    "Ovo",
    "Alike",
    "Fraunces",
    "Lustria",
    "Quando",
    "Coustard",
    "Hepta Slab",
    "Slabo 13px",
    "Podkova",
    "Mallanna",
    "Grand Hotel",
    "Jockey One",
    "Manjari",
    "Grandstander",
    "Petit Formal Script",
    "Zen Maru Gothic",
    "Qwigley",
    "Amiko",
    "Atkinson Hyperlegible",
    "Suranna",
    "Chonburi",
    "Share",
    "Merienda One",
    "Averia Libre",
    "Maitree",
    "Molengo",
    "Seaweed Script",
    "Sunflower",
    "Knewave",
    "Shippori Mincho",
    "Monsieur La Doulaise",
    "Kosugi",
    "Esteban",
    "Wallpoet",
    "Averia Serif Libre",
    "Akshar",
    "Baloo Tamma 2",
    "Bellefair",
    "Calligraffitti",
    "Oxygen Mono",
    "Mate SC",
    "Sniglet",
    "Kite One",
    "Schoolbell",
    "Brawler",
    "Libre Barcode 39",
    "Sofia",
    "Kurale",
    "Dongle",
    "Convergence",
    "Marmelad",
    "Rosario",
    "Aladin",
    "Orelega One",
    "Odibee Sans",
    "Harmattan",
    "Thasadith",
    "Encode Sans Semi Condensed",
    "Spectral SC",
    "Marvel",
    "Metrophobic",
    "DM Mono",
    "Bowlby One",
    "Nova Mono",
    "Mr De Haviland",
    "Proza Libre",
    "Lemon",
    "Livvic",
    "Noto Sans Telugu",
    "Kelly Slab",
    "Dawning of a New Day",
    "Bungee Shade",
    "Radley",
    "Bentham",
    "Calistoga",
    "Stardos Stencil",
    "Hanuman",
    "Noto Sans Hebrew",
    "Waiting for the Sunrise",
    "Oleo Script Swash Caps",
    "Grenze Gotisch",
    "Allan",
    "Gugi",
    "B612 Mono",
    "IM Fell English",
    "Limelight",
    "Gabriela",
    "Cormorant SC",
    "Fanwood Text",
    "ZCOOL XiaoWei",
    "IM Fell DW Pica",
    "UnifrakturMaguntia",
    "Poly",
    "Yatra One",
    "Love Ya Like A Sister",
    "Cutive",
    "Chelsea Market",
    "Gurajada",
    "Goudy Bookletter 1911",
    "Original Surfer",
    "Turret Road",
    "Vesper Libre",
    "Farro",
    "Expletus Sans",
    "Rasa",
    "Mirza",
    "Raleway Dots",
    "Gravitas One",
    "Megrim",
    "Style Script",
    "Noto Sans Kannada",
    "Georama",
    "Buenard",
    "Inknut Antiqua",
    "Happy Monkey",
    "Irish Grover",
    "Mansalva",
    "Codystar",
    "Oregano",
    "Noto Sans Bengali",
    "Zen Kaku Gothic New",
    "Sarpanch",
    "Tenali Ramakrishna",
    "Emilys Candy",
    "Sue Ellen Francisco",
    "Kiwi Maru",
    "Kadwa",
    "Carme",
    "Inder",
    "Source Sans 3",
    "Oxanium",
    "Patrick Hand SC",
    "Federo",
    "Cormorant Upright",
    "Sansita Swashed",
    "Duru Sans",
    "Roboto Flex",
    "Noto Sans Oriya",
    "Almendra",
    "Noto Sans Gujarati",
    "Arya",
    "Euphoria Script",
    "Fahkwang",
    "Galada",
    "Noto Sans Gurmukhi",
    "Reggae One",
    "Andika",
    "Zeyada",
    "B612",
    "KoHo",
    "Fresca",
    "Ranchers",
    "Vollkorn SC",
    "Share Tech",
    "Caladea",
    "Big Shoulders Text",
    "Comforter Brush",
    "IM Fell Double Pica",
    "Montez",
    "Plus Jakarta Sans",
    "Tillana",
    "Clicker Script",
    "Coiny",
    "Rouge Script",
    "Aguafina Script",
    "Rakkas",
    "Major Mono Display",
    "Baloo Thambi 2",
    "Sedgwick Ave",
    "Baloo Chettan 2",
    "Zen Loop",
    "Give You Glory",
    "Meddon",
    "Anaheim",
    "Voces",
    "McLaren",
    "Homenaje",
    "Mouse Memoirs",
    "Fondamento",
    "Cambo",
    "Italiana",
    "Aref Ruqaa",
    "Fjord One",
    "Ceviche One",
    "Gayathri",
    "Salsa",
    "Antic Didone",
    "Katibeh",
    "Numans",
    "Prosto One",
    "Lexend Zetta",
    "Della Respira",
    "Montserrat Subrayada",
    "Roboto Serif",
    "Vast Shadow",
    "Bellota Text",
    "Notable",
    "Supermercado One",
    "Metamorphous",
    "RocknRoll One",
    "Elsie",
    "Goblin One",
    "Lekton",
    "Ledger",
    "Doppio One",
    "Sail",
    "Balthazar",
    "Baumans",
    "Battambang",
    "Flamenco",
    "Freckle Face",
    "Encode Sans Expanded",
    "ZCOOL QingKe HuangYou",
    "Wendy One",
    "Grape Nuts",
    "Tomorrow",
    "Meera Inimai",
    "Montaga",
    "Finger Paint",
    "Orienta",
    "Truculenta",
    "Libre Barcode 39 Extended Text",
    "Noto Sans Sinhala",
    "Shojumaru",
    "Andada Pro",
    "Ma Shan Zheng",
    "Mukta Mahee",
    "Atma",
    "Saira Stencil One",
    "Port Lligat Slab",
    "Artifika",
    "Chau Philomene One",
    "Smokum",
    "Averia Sans Libre",
    "Dokdo",
    "Newsreader",
    "Petrona",
    "Pirata One",
    "Englebert",
    "Ruslan Display",
    "Coda Caption",
    "Recursive",
    "Baloo Paaji 2",
    "Over the Rainbow",
    "Eater",
    "Tienne",
    "Crafty Girls",
    "Dela Gothic One",
    "Geo",
    "Walter Turncoat",
    "Port Lligat Sans",
    "Carrois Gothic SC",
    "Baloo Bhai 2",
    "Faster One",
    "Life Savers",
    "Kodchasan",
    "Asul",
    "Yusei Magic",
    "Bilbo Swash Caps",
    "Pavanam",
    "Timmana",
    "Solway",
    "Amarante",
    "Akaya Telivigala",
    "Iceland",
    "Noto Nastaliq Urdu",
    "Tauri",
    "Trykker",
    "MuseoModerno",
    "Scope One",
    "League Spartan",
    "Overlock SC",
    "Shippori Mincho B1",
    "Delius Swash Caps",
    "Frijole",
    "Mountains of Christmas",
    "Goldman",
    "The Girl Next Door",
    "Imprima",
    "Dynalight",
    "Slackey",
    "Poller One",
    "Bubbler One",
    "Gafata",
    "Headland One",
    "Nova Round",
    "Strait",
    "Charmonman",
    "Just Me Again Down Here",
    "Gaegu",
    "Noto Sans Mono",
    "Peralta",
    "Loved by the King",
    "Germania One",
    "Mako",
    "Shalimar",
    "Mochiy Pop One",
    "DotGothic16",
    "Encode Sans Semi Expanded",
    "Cherry Cream Soda",
    "Nova Square",
    "Cherry Swash",
    "IBM Plex Sans Thai",
    "Libre Barcode 39 Text",
    "Noto Serif Malayalam",
    "Modak",
    "Wire One",
    "Lily Script One",
    "Delius Unicase",
    "Vibur",
    "Spicy Rice",
    "Praise",
    "Glory",
    "Unkempt",
    "Akaya Kanadaka",
    "Manuale",
    "Prociono",
    "Vazirmatn",
    "Kranky",
    "Brygada 1918",
    "Puritan",
    "Lexend Exa",
    "Gamja Flower",
    "Ranga",
    "Kufam",
    "Ibarra Real Nova",
    "League Script",
    "Baloo Bhaina 2",
    "Allison",
    "Mina",
    "Medula One",
    "Cantora One",
    "Denk One",
    "Bigshot One",
    "Bilbo",
    "Jomhuria",
    "Rationale",
    "Ramaraja",
    "Chicle",
    "UnifrakturCook",
    "Baloo Tammudu 2",
    "MedievalSharp",
    "Sarina",
    "Habibi",
    "Trade Winds",
    "Stylish",
    "IM Fell French Canon",
    "Chilanka",
    "Paprika",
    "Oooh Baby",
    "Red Rose",
    "Song Myung",
    "Libre Barcode 128",
    "Sumana",
    "Cute Font",
    "Cormorant Unicase",
    "Uncial Antiqua",
    "Libre Caslon Display",
    "Road Rage",
    "Sulphur Point",
    "Fredoka",
    "Stoke",
    "Asar",
    "Mystery Quest",
    "Azeret Mono",
    "Meie Script",
    "Zilla Slab Highlight",
    "Londrina Outline",
    "Lovers Quarrel",
    "Ribeye",
    "Sancreek",
    "Kotta One",
    "Diplomata SC",
    "Engagement",
    "Kulim Park",
    "Dekko",
    "Sonsie One",
    "New Rocker",
    "Julee",
    "WindSong",
    "Bellota",
    "Khmer",
    "Redressed",
    "Chango",
    "IBM Plex Sans Thai Looped",
    "Macondo Swash Caps",
    "Inria Serif",
    "Sree Krushnadevaraya",
    "Nova Flat",
    "Shanti",
    "Rosarivo",
    "Smooch",
    "Fontdiner Swanky",
    "Kaisei Tokumin",
    "IBM Plex Sans KR",
    "Farsan",
    "Potta One",
    "BIZ UDPGothic",
    "Rowdies",
    "Text Me One",
    "Margarine",
    "Bayon",
    "Big Shoulders Stencil Display",
    "Red Hat Mono",
    "Yeon Sung",
    "Ruluko",
    "Fenix",
    "Besley",
    "Crushed",
    "Stint Ultra Expanded",
    "East Sea Dokdo",
    "Akronim",
    "Zen Old Mincho",
    "Hurricane",
    "IM Fell French Canon SC",
    "Alumni Sans",
    "Averia Gruesa Libre",
    "Offside",
    "League Gothic",
    "Zen Kaku Gothic Antique",
    "Gotu",
    "Sura",
    "Cagliostro",
    "Nokora",
    "Donegal One",
    "Gemunu Libre",
    "Inika",
    "Gorditas",
    "Tourney",
    "Marko One",
    "Elsie Swash Caps",
    "Simonetta",
    "Viaoda Libre",
    "Underdog",
    "Autour One",
    "ZCOOL KuaiLe",
    "M PLUS 1",
    "Iceberg",
    "Hachi Maru Pop",
    "MonteCarlo",
    "IM Fell Great Primer",
    "Milonga",
    "Piazzolla",
    "Monofett",
    "Buda",
    "Condiment",
    "Miniver",
    "Zen Antique",
    "Croissant One",
    "Chathura",
    "Kumar One",
    "Ewert",
    "Varta",
    "Barrio",
    "Stalemate",
    "Rum Raisin",
    "Montagu Slab",
    "Kavoon",
    "Nosifer",
    "Train One",
    "Lakki Reddy",
    "Hahmlet",
    "Kavivanar",
    "Unlock",
    "Swanky and Moo Moo",
    "Ruthie",
    "Qwitcher Grypen",
    "Stick",
    "Sirin Stencil",
    "Libre Barcode 128 Text",
    "Bigelow Rules",
    "Lexend Giga",
    "Mochiy Pop P One",
    "Angkor",
    "Felipa",
    "Vampiro One",
    "Eagle Lake",
    "Molle",
    "Fascinate Inline",
    "Dorsa",
    "Content",
    "Tulpen One",
    "Londrina Shadow",
    "Wellfleet",
    "Griffy",
    "Scheherazade New",
    "Bahianita",
    "Ravi Prakash",
    "Linden Hill",
    "Rhodium Libre",
    "Galdeano",
    "Kantumruy",
    "Chenla",
    "Mogra",
    "Spirax",
    "Devonshire",
    "Mrs Sheppards",
    "Lexend Mega",
    "Baloo Bhaijaan 2",
    "Andika New Basic",
    "Arbutus",
    "Joti One",
    "Modern Antiqua",
    "Ribeye Marrow",
    "Junge",
    "Sahitya",
    "Spline Sans",
    "Beth Ellen",
    "Maiden Orange",
    "Comforter",
    "Diplomata",
    "Gowun Batang",
    "Klee One",
    "Jolly Lodger",
    "Inria Sans",
    "Romanesco",
    "Karantina",
    "Jomolhari",
    "IM Fell DW Pica SC",
    "Plaster",
    "Piedra",
    "Smythe",
    "Rubik Glitch",
    "Caesar Dressing",
    "Peddana",
    "Metal Mania",
    "Almendra SC",
    "Poor Story",
    "Risque",
    "Radio Canada",
    "Noto Sans Georgian",
    "Revalia",
    "M PLUS 2",
    "Keania One",
    "Zen Dots",
    "Bona Nova",
    "Ephesis",
    "Lancelot",
    "Noto Sans Myanmar",
    "Galindo",
    "Licorice",
    "Syne Mono",
    "Bahiana",
    "Zen Kurenaido",
    "Kirang Haerang",
    "Otomanopee One",
    "Jim Nightshade",
    "Grenze",
    "Kaisei Decol",
    "Noto Serif Thai",
    "Girassol",
    "Shippori Antique",
    "Hanalei",
    "Srisakdi",
    "Londrina Sketch",
    "Oldenburg",
    "Nerko One",
    "Emblema One",
    "Odor Mean Chey",
    "Kaisei Opti",
    "Beau Rivage",
    "IM Fell Great Primer SC",
    "Glass Antiqua",
    "Princess Sofia",
    "Hanalei Fill",
    "Jacques Francois Shadow",
    "Moul",
    "Asset",
    "Birthstone",
    "Noto Emoji",
    "Noto Sans Gothic",
    "Dangrek",
    "Trochut",
    "Atomic Age",
    "Noto Sans Symbols",
    "Nova Slim",
    "Flavors",
    "Hina Mincho",
    "Rampart One",
    "Yomogi",
    "Metal",
    "Lacquer",
    "Noto Sans Armenian",
    "Square Peg",
    "Kumar One Outline",
    "Jacques Francois",
    "Yaldevi",
    "Barriecito",
    "Mohave",
    "Snippet",
    "Libre Bodoni",
    "Big Shoulders Stencil Text",
    "Siemreap",
    "Libre Barcode 39 Extended",
    "Freehand",
    "Miss Fajardose",
    "Zhi Mang Xing",
    "Murecho",
    "Water Brush",
    "Aubrey",
    "GFS Neohellenic",
    "Carattere",
    "Festive",
    "Chela One",
    "Fuggles",
    "Almendra Display",
    "Sedgwick Ave Display",
    "Black And White Picture",
    "Dr Sugiyama",
    "Benne",
    "Butterfly Kids",
    "Bungee Outline",
    "Mr Bedfort",
    "Shippori Antique B1",
    "Gidugu",
    "Seymour One",
    "Erica One",
    "Liu Jian Mao Cao",
    "Fascinate",
    "New Tegomin",
    "Astloch",
    "Sunshiney",
    "Bungee Hairline",
    "Bonbon",
    "Suwannaphum",
    "Birthstone Bounce",
    "Sofadi One",
    "Bakbak One",
    "Lexend Tera",
    "Vujahday Script",
    "Stalinist One",
    "Nova Oval",
    "Fruktur",
    "Snowburst One",
    "Encode Sans SC",
    "Combo",
    "Passero One",
    "Taprom",
    "Bokor",
    "Smooch Sans",
    "IM Fell Double Pica SC",
    "Tapestry",
    "Texturina",
    "Neonderthaw",
    "Familjen Grotesk",
    "Vibes",
    "BioRhyme Expanded",
    "Noto Serif Kannada",
    "Miltonian",
    "Anybody",
    "Corinthia",
    "Gowun Dodum",
    "Nova Cut",
    "Zen Antique Soft",
    "Kaisei HarunoUmi",
    "Qahiri",
    "Gluten",
    "Ms Madi",
    "Gupter",
    "Inspiration",
    "M PLUS 1 Code",
    "Butcherman",
    "Suravaram",
    "Nova Script",
    "Long Cang",
    "BIZ UDPMincho",
    "Federant",
    "Miltonian Tattoo",
    "Ruge Boogie",
    "Moulpali",
    "Rubik Microbe",
    "Noto Sans Math",
    "Luxurious Script",
    "Imbue",
    "Geostar Fill",
    "Mea Culpa",
    "Lexend Peta",
    "Purple Purse",
    "Big Shoulders Inline Text",
    "Anek Devanagari",
    "Updock",
    "The Nautigal",
    "BIZ UDGothic",
    "Ballet",
    "Bonheur Royale",
    "Langar",
    "Whisper",
    "Rock 3D",
    "Noto Serif Tamil",
    "Gwendolyn",
    "Single Day",
    "Sevillana",
    "Dhurjati",
    "Kdam Thmor",
    "Yuji Syuku",
    "Fasthand",
    "Rubik Moonrocks",
    "Rubik Beastly",
    "Noto Sans Tamil Supplement",
    "Preahvihear",
    "Kenia",
    "BIZ UDMincho",
    "Syne Tactile",
    "Anek Tamil",
    "Petemoss",
    "Rubik Wet Paint",
    "Noto Serif Devanagari",
    "Gideon Roman",
    "Waterfall",
    "Noto Sans Symbols 2",
    "My Soul",
    "Xanh Mono",
    "Imperial Script",
    "Send Flowers",
    "Hubballi",
    "Fuzzy Bubbles",
    "Stick No Bills",
    "Luxurious Roman",
    "Zen Tokyo Zoo",
    "Trispace",
    "Moon Dance",
    "Geostar",
    "Meow Script",
    "Lavishly Yours",
    "Genos",
    "Libre Barcode EAN13 Text",
    "Grechen Fuemen",
    "Koh Santepheap",
    "Shizuru",
    "Warnes",
    "IBM Plex Sans Devanagari",
    "Are You Serious",
    "Big Shoulders Inline Display",
    "Noto Serif Georgian",
    "Babylonica",
    "Anek Bangla",
    "Cherish",
    "Alumni Sans Inline One",
    "Ingrid Darling",
    "Noto Serif Nyiakeng Puachue Hmong",
    "Palette Mosaic",
    "Rubik Bubbles",
    "Anek Gujarati",
    "Noto Sans Lao",
    "Noto Sans Tai Viet",
    "Noto Sans Javanese",
    "Oi",
    "IBM Plex Sans Hebrew",
    "BhuTuka Expanded One",
    "Rubik Puddles",
    "Fleur De Leah",
    "Ole",
    "Anek Gurmukhi",
    "Noto Serif Armenian",
    "Moo Lah Lah",
    "Anek Telugu",
    "Anek Malayalam",
    "Love Light",
    "Anek Latin",
    "Twinkle Star",
    "Anek Odia",
    "Noto Sans Old North Arabian",
    "Passions Conflict",
    "Anek Kannada",
    "Yuji Mai",
    "Yuji Boku",
    "Noto Music",
    "Estonia",
    "Flow Circular",
    "Noto Sans Egyptian Hieroglyphs",
    "Noto Serif Khmer",
    "Noto Sans Deseret",
    "Island Moments",
    "Noto Sans Coptic",
    "Grey Qo",
    "Uchen",
    "Kolker Brush",
    "Explora",
    "Noto Sans Saurashtra",
    "M PLUS Code Latin",
    "Noto Sans Thaana",
    "Caramel",
    "Kings",
    "Noto Sans Anatolian Hieroglyphs",
    "Noto Serif Gujarati",
    "Noto Sans Meetei Mayek",
    "Redacted Script",
    "Puppies Play",
    "Yuji Hentaigana Akebono",
    "Noto Serif Sinhala",
    "Sassy Frass",
    "Noto Serif Ethiopic",
    "Noto Sans Carian",
    "Flow Block",
    "Flow Rounded",
    "Noto Sans Thai Looped",
    "Yuji Hentaigana Akari",
    "Noto Sans Cherokee",
    "Noto Serif Hebrew",
    "Noto Sans Adlam",
    "Noto Rashi Hebrew",
    "Noto Serif Telugu",
    "Noto Serif Lao",
    "Noto Sans Tagalog",
    "Noto Sans Imperial Aramaic",
    "Redacted",
    "Noto Sans Brahmi",
    "Noto Serif Myanmar",
    "Noto Sans Elbasan",
    "Noto Sans Limbu",
    "Noto Sans Khmer",
    "Noto Sans Rejang",
    "Noto Sans Lepcha",
    "Noto Traditional Nushu",
    "Noto Sans Miao",
    "Noto Sans Hanunoo",
    "Noto Sans Cham",
    "Noto Sans Bamum",
    "Noto Sans Osage",
    "Noto Sans Multani",
    "Noto Sans Old Turkic",
    "Noto Sans Mahajani",
    "Noto Sans Lycian",
    "Noto Sans Tai Tham",
    "Noto Sans Ol Chiki",
    "Noto Serif Tibetan",
    "Noto Serif Gurmukhi",
    "Noto Sans Old Hungarian",
    "Noto Sans Canadian Aboriginal",
    "Noto Sans Batak",
    "Noto Serif Yezidi",
    "Noto Sans Sora Sompeng",
    "Noto Sans Marchen",
    "Noto Sans Cypriot",
    "Noto Sans Khojki",
    "Noto Sans Tagbanwa",
    "Noto Sans Buginese",
    "Noto Sans Shavian",
    "Noto Sans Adlam Unjoined",
    "Noto Sans Yi",
    "Noto Sans Tirhuta",
    "Noto Sans Mongolian",
    "Noto Sans Old Italic",
    "Noto Sans Old Persian",
    "Noto Sans Lisu",
    "Noto Sans Medefaidrin",
    "Noto Sans Balinese",
    "Noto Sans Elymaic",
    "Noto Sans Sogdian",
    "Noto Sans Psalter Pahlavi",
    "Noto Serif Balinese",
    "Noto Sans Inscriptional Pahlavi",
    "Noto Sans Zanabazar Square",
    "Noto Sans Ogham",
    "Noto Sans Sundanese",
    "Noto Sans Inscriptional Parthian",
    "Noto Sans Samaritan",
    "Noto Sans Old South Arabian",
    "Noto Sans Kaithi",
    "Noto Sans Wancho",
    "Noto Sans Hanifi Rohingya",
    "Noto Sans Kayah Li",
    "Noto Sans Tifinagh",
    "Noto Serif Ahom",
    "Noto Sans Palmyrene",
    "Noto Sans Grantha",
    "Noto Sans Avestan",
    "Noto Serif Dogra",
    "Noto Sans Mro",
    "Noto Sans Indic Siyaq Numbers",
    "Noto Serif Tangut",
    "Noto Sans Syriac",
    "Noto Serif Grantha",
    "Noto Sans Cuneiform",
    "Noto Sans Mayan Numerals",
    "Noto Sans N Ko",
    "Noto Sans Bassa Vah",
    "Noto Sans Caucasian Albanian",
    "Noto Sans Osmanya",
    "Noto Sans Pahawh Hmong",
    "Noto Sans New Tai Lue",
    "Noto Sans Linear B",
    "Noto Sans Kharoshthi",
    "Noto Sans Tai Le",
    "Noto Sans Newa",
    "Noto Sans Old Permic",
    "Noto Sans Khudawadi",
    "Noto Sans Pau Cin Hau",
    "Noto Sans Soyombo",
    "Noto Sans Glagolitic",
    "Noto Sans Phoenician",
    "Noto Sans Nushu",
    "Noto Sans Chakma",
    "Noto Sans Bhaiksuki",
    "Noto Sans Masaram Gondi",
    "Noto Sans Manichaean",
    "Noto Sans Meroitic",
    "Noto Sans Mandaic",
    "Noto Sans Siddham",
    "Noto Sans Nabataean",
    "Noto Sans Runic",
    "Noto Sans Old Sogdian",
    "Noto Sans Warang Citi",
    "Noto Sans Modi",
    "Noto Sans Lydian",
    "Noto Sans Duployan",
    "Noto Sans Vai",
    "Noto Sans Buhid",
    "Noto Sans Syloti Nagri",
    "Noto Sans Ugaritic",
    "Noto Sans Sharada",
    "Noto Sans Linear A",
    "Noto Sans Gunjala Gondi",
    "Noto Sans Phags Pa",
    "Noto Sans Hatran",
    "Noto Sans Takri"
]

